version: "3.8"
services:
  healthcheck:
    image: ghcr.io/s-wasser/healthcheck
    container_name: healthcheck
    volumes:
      - ./config:/config
    environment:
      - TZ=America/Toronto
    restart: unless-stopped